language: python

dist: trusty
sudo: required

python:
  - "3.5"

install:
  - sudo apt install libdb5.3-dev
  - pip install requests configargparse bcrypt bsddb3
  - pip install coverage nose rednose

script:
  - nosetests --with-coverage --cover-xml --cover-package=xclib

after_success:
- bash <(curl -s https://codecov.io/bash)
